Module3 task3
htmlacademy-nodejs/231833-typoteka-3 pull request #9
Opened 2020-03-24 21:25 UTC by mazovladimir

2020-03-28 21:35 UTC, cmpxchg16b requested changes

2020-03-28 21:35 UTC, cmpxchg16b commented on src/express/index.js
> +// "use strict";
код не следует комментировать в гите =)

2020-03-28 21:35 UTC, cmpxchg16b commented on src/routes/posts.js
> +const FILENAME = `mocks.json`;
константы лучше изолировать в отдельном файле

2020-03-28 21:35 UTC, cmpxchg16b commented on src/routes/posts.js
> +postRouter.get(`/`, async (req, res) => {
в третьем экспрессе, он не умеет правильно до конца работать с асинхронными роутами. поэтому асинхронные обработчики следует оборачивать в специальную функцию, которая прокидывает ошибку дальше в цепочку

const withAsync = fn => (req, res, next) => {
  Promise.resolve(fn(req, res, next)).catch(next);
};

но я не знаю, проходили ли вы это уже, плюс ты обернуд в try/catch поэтому в 90% кейзов это будет работать нормально

2020-03-30 12:45 UTC, mazovladimir commented on src/routes/posts.js
> +postRouter.get(`/`, async (req, res) => {
не говорили про это, я и другие курсы смотрел, там тоже так делают, и в учебнике так, а почему проблема ?

2020-03-30 12:45 UTC, mazovladimir commented on src/routes/posts.js
> +postRouter.get(`/`, async (req, res) => {
а все понял )))

2020-03-30 18:15 UTC, cmpxchg16b commented on src/routes/posts.js
> +postRouter.get(`/`, async (req, res) => {
проблема в том, что если в catch повторная ошибка будет, запрос повиснет

2020-03-30 18:21 UTC, cmpxchg16b approved these changes
я приму задание, раз в материалах нет того как работать с асинхронными роутами, но в следующий раз пожалуйста сделай как я показал. Могу рассказать подробнее, если хочешь.

2020-03-30 18:22 UTC, merged